### ISSUE TITLE
missing positional argument langs

### ISSUE THREAD

**Issue by architlatkar27** [anjbapat/D2T#1]
```
Traceback (most recent call last):
  File "Train/train.py", line 893, in <module>
    main(args)
  File "Train/train.py", line 825, in main
    encoder, decoder = train(train_data, train_lang, **parameters)
  File "Train/train.py", line 418, in train
    model = Seq2Seq(encoder, decoder, train_func, criterion, embedding_size, langs)
TypeError: __init__() missing 1 required positional argument: 'langs'
```
I was running the project on google colab when i got this error. How can i resolve it?

**Comment by yuanyuan12080317** [comment]
我也遇到了同样的问题，你解决了吗

**Comment by kaushan** [comment]
got that too - use train1.py instead ...
